### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by paugalles** [piclem/sen2venus#3]
Do you have pretrained weights for the case of [fork of sr-pytorch-lightning](https://github.com/piclem/sr-pytorch-lightning)?

I have tried to train it in google colab with a small portion of the dataset and with a couple of epochs and it works fine, thanks you for that! I just wonder if you already have the pretrained weights so that we can reduce footprint and make it more accessible.

**Comment by paugalles** [comment]
I have found these pretrained weights here:
https://github.com/Evoland-Land-Monitoring-Evolution/sentinel2_superresolution/tree/master/models

**Comment by piclem** [comment]
@paugalles thanks for your feedback and infos. The repository you found is the official, most recent release by original researchers so if it fits your needs you should go for it (I do not guarantee compatibility between the forked and their CARN implementation/weights). 
I need to check their latest implementation (it includes SWIR bands, so the networks might have more inputs/outputs compared with the 4 or 8 bands here) and see if this repo can still complement theirs with the latest dataset version (e.g. for NN architectures comparison).
